### PR TITLE
add support for overriding swagger UI rendering

### PR DESCRIPTION
**Pull request by blynn99**
Adds support for overriding a few swagger.html components.
* favicon
* page title
* whether to render the top bar

### CODE REVIEW

**Comment by blynn99** [comment]
Note this PR is more about presenting a few ideas.  The main idea is to support customizing the rendered swagger UI.

**Comment by luolingchun** [comment]
Thanks, @blynn99 

I have an unimplemented idea before, add a `ui_templates` parameter is used to overwrite or add custom UI templates.

```python
ui_templates: Optional[Dict[str, str]] = None


ui_templates = {
    "swagger": swagger_html_string,
    "rapipdf": rapipdf_html_string
}

app = OpenAPI(__name__, info=info, ui_templates=ui_templates)
```

`swagger_html_string` will replace the original swagger template, and `rapipdf_html_string` is a new template.

You can use `swagger_html_string` does anything. What do you think?

**Comment by luolingchun** [comment]
By the way, I am enjoying the Chinese New Year. If you agree with me, you can continue to do it

**Comment by blynn99** [comment]
@luolingchun I like you idea of using `swagger_html_string` and `rapipdf_html_string` better than my ideas.  Your approach gives the developer more control.   I'm going to close my merge request. 

I hope you continue to have a wonderful Chinese New Year.

**Comment by blynn99** [comment]
Closing request as there is a better solution

**Pull request closed without merging**
