### PR TITLE
[#17] Support for Nested APIBlueprint enhancement

### PR DESCRIPTION
**Pull request by luolingchun**
Support for Nested APIBlueprint enhancement

### CODE REVIEW

**Comment by luolingchun** [comment]
todo: Update documentation about Nested APIBlueprint

**Comment by dvaerum** [comment]
Hey @luolingchun, I have been working with your patch for the most of the week, and it seems to work, the only thing I have found is the order of when one does what, but if the right order is followed it works :D

Maybe it makes sense to have a way to do call-backs. E.g. if I add an endpoint `endpoint_1` to an `APIBlueprint` name `child` and when register that `APIBlueprint` at one name `parent` I cannot afterwords add another endpoint (`endpoint_2`) to the `child`
```python
from flask_openapi3 import APIBlueprint

parent = APIBlueprint(name="parent", import_name=__name__, url_prefix="/parent")

child = APIBlueprint(name="child", import_name=__name__, url_prefix="/child")

@child.post(rule="endpoint_1", responses={"204": MsgResponse, "400": ErrorMsgResponse})
def endpoint_1(body: PostRequest):
    return {"msg": "test msg"}

parent.register_api(child)

@child.post(rule="endpoint_2", responses={"204": MsgResponse, "400": ErrorMsgResponse})
def endpoint_2(body: PostRequest):
    return {"msg": "test msg"}
```

**Comment by luolingchun** [comment]
@dvaerum There is the same problem in **Flask**, Therefore, I think we should solve this problem by ourselves when coding.

```python
from flask import Flask, Blueprint


app = Flask(__name__)
bl = Blueprint('test', __name__)


@bl.route('/route1')
def route1():
    return 'Hello, World!'


app.register_blueprint(bl)


@bl.route('/route2')
def route2():
    return 'Hello, World!'


if __name__ == '__main__':
    print(app.url_map)
```

```
Map([<Rule '/route1' (GET, HEAD, OPTIONS) -> test.route1>,
 <Rule '/static/<filename>' (GET, HEAD, OPTIONS) -> static>])
```

**Comment by dvaerum** [comment]
Sounds completely fair

**Comment by dvaerum** [comment]
@luolingchun I have been using this patch of yours for some time now and still have not found any problems with it :+1:  Just want to give you an update :smiley:

**Comment by luolingchun** [comment]
@dvaerum I made a preview release [v2.0.0rc1](https://github.com/luolingchun/flask-openapi3/releases/tag/v2.0.0rc1).

**Pull request closed without merging**
